type PullRequest = {
  id: number;
  title: string;
  author: string;
  authorImg: string;
  created: string;
  reviewers: string;
  reviewersImg: string;
  date: string;
};

const exampleData: PullRequest[] = [
  {
    id: 1,
    title: "Pull Request 23",
    author: "Alec",
    authorImg: "(img)",
    created: "21 min ago",
    reviewers: "Commended",
    reviewersImg: "(img)",
    date: "26 avr il",
  },
  {
    id: 2,
    title: "Flux fix git list",
    author: "Aleq",
    authorImg: "(img)",
    created: "5 days ago",
    reviewers: "Champmemases",
    reviewersImg: "(img)",
    date: "42 avr il",
  },
  {
    id: 3,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 4,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 5,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 6,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 7,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 8,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 9,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 10,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 11,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 12,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 13,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 14,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 15,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 16,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 17,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 18,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 19,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 20,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 21,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 22,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
  {
    id: 23,
    title: "Review Commit",
    author: "Alxaan",
    authorImg: "(img)",
    created: "23 days ago",
    reviewers: "Created",
    reviewersImg: "(img)",
    date: "23 avr il",
  },
];

export default exampleData;
